import { useState } from 'react';
import { Camera, Check, Mail, MapPin, Phone, Send, X } from 'lucide-react';
import { services } from '../data';

const contactData = [
  { label: 'Instagram', value: '@arcanjo_peliculas_', href: 'https://www.instagram.com/arcanjo_peliculas_/', icon: Camera },
  { label: 'WhatsApp', value: '+55 (63) 99256-5126', href: 'https://wa.me/5563992565126', icon: Phone },
  { label: 'E-mail', value: 'contato@arcanjopeliculas.com', href: 'mailto:contato@arcanjopeliculas.com', icon: Mail },
  { label: 'Endereço', value: 'Floresta do Araguaia, Pará', href: 'https://www.google.com/maps/search/?api=1&query=Rua+04+Floresta+do+Araguaia+PA+68543-000', icon: MapPin },
];

export function Services() { return <section id="servicos" className="section services"><div className="section-head reveal"><div><div className="section-kicker"><span>03</span><b>O que fazemos</b></div><h2>Forma, função<br /><em>e atitude.</em></h2></div><p>Materiais de alta performance e mão de obra que entende que o detalhe é o todo.</p></div><div className="service-grid">{services.map((service) => <article className="service-card reveal" key={service.number}><div className="service-top"><span>{service.number}</span><b>{service.icon}</b></div><h3>{service.title}</h3><p>{service.text}</p><span className="service-arrow">↗</span></article>)}</div></section> }

export function Contact() { const [form, setForm] = useState({}); const [sent, setSent] = useState(false); const [errors, setErrors] = useState({}); const submit = (event) => { event.preventDefault(); const required = ['name', 'phone', 'email', 'vehicle', 'message']; const next = Object.fromEntries(required.filter((key) => !form[key]?.trim()).map((key) => [key, 'Preencha este campo'])); setErrors(next); if (!Object.keys(next).length) { const text = encodeURIComponent(`Olá, Arcanjo Películas!\n\nNome: ${form.name}\nTelefone: ${form.phone}\nE-mail: ${form.email}\nVeículo: ${form.vehicle}\nProjeto: ${form.message}`); window.open(`https://wa.me/5563992565126?text=${text}`, '_blank', 'noopener,noreferrer'); setSent(true); } }; const change = (event) => { setForm({ ...form, [event.target.name]: event.target.value }); setErrors({ ...errors, [event.target.name]: '' }); }; return <section id="contato" className="section contact"><div className="contact-intro reveal"><div className="section-kicker"><span>06</span><b>Seu briefing</b></div><h2>Seu próximo<br /><em>projeto começa aqui.</em></h2><p>Conte para a gente o que você imaginou. Ao enviar, seu briefing será montado para o WhatsApp da equipe.</p></div><form className="contact-form reveal reveal-delay" onSubmit={submit} noValidate>{sent ? <div className="success"><span><Check /></span><h3>Briefing preparado.</h3><p>Sua mensagem foi aberta no WhatsApp para envio.</p><button type="button" className="text-link" onClick={() => { setSent(false); setForm({}); }}>Enviar outro briefing</button></div> : <><div className="form-row"><label>Seu nome<input name="name" value={form.name || ''} onChange={change} placeholder="Como podemos chamar você?" />{errors.name && <small>{errors.name}</small>}</label><label>Telefone<input name="phone" value={form.phone || ''} onChange={change} placeholder="(00) 00000-0000" />{errors.phone && <small>{errors.phone}</small>}</label></div><div className="form-row"><label>E-mail<input name="email" type="email" value={form.email || ''} onChange={change} placeholder="voce@email.com" />{errors.email && <small>{errors.email}</small>}</label><label>Veículo<input name="vehicle" value={form.vehicle || ''} onChange={change} placeholder="Marca e modelo" />{errors.vehicle && <small>{errors.vehicle}</small>}</label></div><label>Fale sobre o projeto<textarea name="message" value={form.message || ''} onChange={change} placeholder="Cor, acabamento, referências..." rows="4" />{errors.message && <small>{errors.message}</small>}</label><button className="button button-gold submit" type="submit"><span>Enviar briefing</span><Send size={16} /></button></>}</form></section> }

export function ContactHub() { return <section id="contatos" className="section contact-hub"><div className="contact-hub-intro reveal"><div className="section-kicker"><span>07</span><b>Fale com a Arcanjo</b></div><h2>Conecte-se<br /><em>com a gente.</em></h2><p>Escolha o canal que preferir. Estamos prontos para ouvir sua próxima ideia.</p></div><div className="contact-card-grid">{contactData.map(({ label, value, href, icon: Icon }) => <a className="contact-card reveal" href={href} target={href.startsWith('http') ? '_blank' : undefined} rel={href.startsWith('http') ? 'noreferrer' : undefined} key={label}><Icon size={21} /><span><small>{label}</small><strong>{value}</strong></span><b>↗</b></a>)}</div></section> }

export function Location() { return <section id="localizacao" className="section location"><div className="location-copy reveal"><div className="section-kicker"><span>08</span><b>Onde estamos</b></div><h2>Venha nos<br /><em>encontrar.</em></h2><p>Nosso espaço está em Floresta do Araguaia, no Pará. Consulte o mapa para planejar sua visita.</p><div className="location-details"><div><MapPin size={18} /><span><small>Endereço</small>RUA. 04 Floresta do Araguaia - PA, 68543-000</span></div><div><MapPin size={18} /><span><small>Cidade</small>Floresta do Araguaia, Pará</span></div><div><Phone size={18} /><span><small>Horário de funcionamento</small>Seg - Sex: 09:00 - 19:00<br />Sáb: 09:00 - 17:00</span></div></div><a className="button button-line" href="https://www.google.com/maps/search/?api=1&query=Rua+04+Floresta+do+Araguaia+PA+68543-000" target="_blank" rel="noreferrer"><span>Como chegar</span><MapPin size={16} /></a></div><div className="map-frame reveal reveal-delay"><iframe title="Localização da Arcanjo Películas no Google Maps" src="https://www.google.com/maps?q=Rua+04,+Floresta+do+Araguaia,+PA,+68543-000&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></section> }

export function Footer({ go }) { return <footer><div className="footer-main"><button className="brand" onClick={() => go('inicio')}><span className="brand-mark">A</span><span>ARCANJO<small>PELÍCULAS</small></span></button><p>Transformações que deixam<br />uma marca.</p><button className="back-top" onClick={() => go('inicio')}>Voltar ao topo ↑</button></div><div className="footer-bottom"><span>© 2024 Arcanjo Películas</span><span>Estética automotiva & envelopamento</span><a href="https://www.instagram.com/arcanjo_peliculas_/" target="_blank" rel="noreferrer">Instagram ↗</a></div></footer> }

export function Lightbox({ src, close }) { if (!src) return null; return <div className="lightbox" role="dialog" aria-modal="true" onClick={close}><div className="lightbox-card" onClick={(event) => event.stopPropagation()}><button onClick={close} aria-label="Fechar imagem"><X /></button><img src={src} alt="Projeto ampliado" /></div></div> }


